**Yash Bhati (2511022250058)**


**Task 3** — Convolution using im2col

In [2]:
import numpy as np

def im2col(image, kernel_size, stride=1, padding=0):

    if padding > 0:
        image = np.pad(
            image,
            ((padding, padding), (padding, padding)),
            mode="constant"
        )

    H, W = image.shape

    out_h = (H - kernel_size) // stride + 1
    out_w = (W - kernel_size) // stride + 1

    cols = []

    for i in range(0, out_h * stride, stride):
        for j in range(0, out_w * stride, stride):

            patch = image[
                i:i + kernel_size,
                j:j + kernel_size
            ]

            cols.append(patch.flatten())

    return np.array(cols)


# Input image
image = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

kernel = np.array([
    [1, 0],
    [0, -1]
])

# Convert image to columns
cols = im2col(image, 2)

# Convolution using matrix multiplication
result = cols @ kernel.flatten()

# Reshape output
result = result.reshape(3, 3)

print("Convolution Output:")
print(result)

Convolution Output:
[[-5 -5 -5]
 [-5 -5 -5]
 [-5 -5 -5]]
